### PR TITLE
sublocales

### PR DESCRIPTION
**Pull request by dan323**
Added some sublocales to avoid carrying `group0` around all the time

### CODE REVIEW

**Comment by dan323** [comment]
@SKolodynski do you approve? I am working on ring ideals next.

**Comment by SKolodynski** [comment]
Sorry I did not notice there are new PR's. I will review them in the next couple of days.

**Comment by dan323** [comment]
@SKolodynski I am not finished with the one about ideals.

**Comment by SKolodynski** [comment]
This PR has been [merged](https://github.com/SKolodynski/IsarMathLib/commits/master). I did the merge locally, then applied some changes and pushed the result to GH. I am not sure how can I tell GitHub that so that it does not show these conflicts. If you have an idea for a workflow such that I can modify and merge locally and GitHub knows the PR has been merged please let me know.

**Comment by dan323** [comment]
You pushed master after merging locally? That will not work. Close this PR

**Pull request closed without merging**
