### PR TITLE
side uniformities for topological groups

### PR DESCRIPTION
**Pull request by dan323**
Here is the proof for the existence of the left and right uniformities for topological groups.

### CODE REVIEW

**Comment by dan323** [comment]
I did not know what branch to merge to.

**Comment by SKolodynski** [comment]
Pull requests against master are ok, I will merge each into its own branch anyway.

**Comment by SKolodynski** [comment]
I am thinking maybe it would be more convenient if I create a special branch for you to send pull requests to? I have to read a bit how this is typically done.

**Comment by SKolodynski** [comment]
Turns out I can check out your pull request locally without creating any new branches on GitHub. So, for the IsarMathLib scale sending pull requests to master is fine.

**Comment by SKolodynski** [comment]
After merging I got
`*** Undefined fact: "group0_5_L1" (line 281 of "~/Projects/IsarMathLib/git/IsarMathLib/TopologicalGroup_ZF.thy")`

Must be something in your fork that I changed in mine.  Can you give me some string from the source of  the group0_5_L1 lemma in your fork so that I can search how is it called now in mine?

**Comment by dan323** [comment]
lemma (in group0) group0_5_L1: assumes A1: "g\<in>G"
  shows "RightTranslation(G,P,g) : G\<rightarrow>G" and  "LeftTranslation(G,P,g) : G\<rightarrow>G"
proof -
  from A1 have "\<forall>a\<in>G. a\<cdot>g \<in> G" and "\<forall>a\<in>G. g\<cdot>a \<in> G"
    using group_oper_assocA apply_funtype by auto
  then show 
    "RightTranslation(G,P,g) : G\<rightarrow>G" 
    "LeftTranslation(G,P,g) : G\<rightarrow>G"
    using RightTranslation_def LeftTranslation_def func1_1_L11A
    by auto
qed

**Pull request merged**
