### PR TITLE
Roelcke uniformity

### PR DESCRIPTION
**Pull request by dan323**
1. Left and right translations uniformly continuous in their respective uniformities. 
2. Roelcke uniformity

Partially solves #4

### CODE REVIEW

**Comment by SKolodynski** [comment]
I got 
`
*** Failed to refine any pending goal
*** At command "by" (line 494 of "~/Projects/IsarMathLib/IsarMathLib_git/IsarMathLib/TopologicalGroup_Uniformity_ZF.thy")
`
after merge. I have fixed  that but some element of the pull request process is still missing.

**Comment by dan323** [comment]
What is missing?

**Comment by SKolodynski** [comment]
I imagine you have some workflow (process) for generating a pull request. It would be good if the result of applying the changes provided in the pull request always resulted in sources that can be verified with Isabelle. This is currently not the case as this error (easy to [fix](https://github.com/SKolodynski/IsarMathLib/commit/c17815fbdb6d7b185ec6a8be6c2187a3883e5432)) shows. Something is missing in the process on your side.

**Comment by dan323** [comment]
In this case I had to add a second commit to update to your master. This commit was done on github side. My original commit was working.

**Comment by dan323** [comment]
Next time, in case of a second commit, I will do it on my side.

**Pull request merged**
